# Generated by Django 4.2.7 on 2023-11-25 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_alter_store_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openinghours",
            unique_together=set(),
        ),
    ]
